### ISSUE TITLE
Question about EVA module

### ISSUE THREAD

**Issue by greatbaozi001** [zhenliuZJU/EVA-Gaussian#1]
Thanks for your great work! I have some questions regarding the EVA module.

In `./lib/attention_unet.py`, lines 133-149:

```python
x = torch.roll(x, shifts=self.window_size//2, dims=2)
x = rearrange(x, 'b v (p w) c -> (b p) v w c', w=self.window_size)  
y = rearrange(y, 'b v (p w) c -> (b p) v w c', w=self.window_size)          
xv1, xv2 = x[:,0], x[:,1]
yv1, yv2 = y[:,0], y[:,1]
yv1 = yv1.permute(1, 0, 2)
yv2 = yv2.permute(1, 0, 2)
xv1 = xv1.permute(1, 0, 2)
xv2 = xv2.permute(1, 0, 2)
v1 = self.attn_1(yv1, yv2, xv1, need_weights=False, attn_mask=attn_mask)[0] 
v1 = v1.permute(1, 0, 2)             

v2 = self.attn_2(yv2, yv1, xv2, need_weights=False, attn_mask=attn_mask)[0] 
v2 = v2.permute(1, 0, 2)
x = torch.cat((v1.unsqueeze(dim=1), v2.unsqueeze(dim=1)), dim=1)
x = rearrange(x, '(b l) v w c -> b v (l w) c', l=l//self.window_size, w=self.window_size)
x = torch.roll(x, shifts=-self.window_size//2, dims=2)
```

1. Why does the attention module use v1 as the query and value, and v2 as the key? In most cases, the value and key should come from the same feature map.
2. Why is only x rolled, but y is fixed? Is there a particular reason for this?

I would appreciate any clarification. Thanks again for your great work!

**Comment by zhenliuZJU** [comment]
Thank you for the question.

**Question 1:** We have experimented with various versions of cross-attention, including cross key & value, cross value, and cross key attention. Each type of attention facilitates different forms of information merging. In our approach, we utilize cross key attention to enhance the exchange of information between features. Our experiments indicate that cross key attention performs slightly better than the other variants, though the difference is not significant.

**Question 2:**  The second stage is designed to expand the receptive field of our window-embedded attention. By shifting only in x and not in y, we allow for information exchange between pixels that are farther apart. If both x and y are shifted, the attention remains localized to nearby pixels. We have a revised version of the paper that explains this concept more clearly, and it will be released soon.

I hope this answers your questions.
